db:
  url: jdbc:postgresql://localhost:5433/check_repositotory
  user: postgres
  password: postgres
  driver: org.postgresql.Driver

hibernate:
    show: true
    format: true
    dialect: org.hibernate.dialect.PostgreSQL10Dialect